name = "student-cloudflare-app"

main = "worker.js"

compatibility_date = "2026-05-21"

[[d1_databases]]
binding = "DB"
database_name = "student-db"
database_id = "72588300-19f9-466f-a7b4-277cde66dc9e"
